### ISSUE TITLE
Error in sort.list(y) : 'x' must be atomic for 'sort.list' Have you call 'sort' on a list ? 

### ISSUE THREAD

**Issue by cregouby** [sambaala/linkspotter#2]
Hello, 

Linkspotter is impressive, but fails with the following error in some standard (dplyr) datasets : 
```
library(dplyr)
linkspotterComplete(nasa)
[1] "Number of variables: 4"
[1] "Number of couples: 6"
[1] "Number of observations: 41472"
[1] "Start time: 2017-06-27 00:03:15"
Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?
```

```
linkspotterComplete(starwars)
[1] "Number of variables: 13"
[1] "Number of couples: 78"
[1] "Number of observations: 87"
[1] "Start time: 2017-06-27 00:07:12"
Error in sort.list(y) : 'x' must be atomic for 'sort.list'
Have you called 'sort' on a list?
```

Any clue how to fix it or workaround ? 
Thanks  lot for your efforts, 
C.R.

**Comment by sambaala** [comment]
Hello,

Thanks for your report.
linkspotterComplete() is, for now, awaiting for a data.frame. So you need to convert the data beforehand as following:

On "nasa" dataset,
```{r eval=FALSE}
nasa_df<-tbl_df(nasa)
linkspotterComplete(nasa_df, corMethods = c("pearson","spearman"))$run_it
```
I only use "pearson" and "spearman" coefficients here because "kendall", "MIC" and "maxMNI" are taking much time when the number of rows is big.

On "starwars" dataset,
```{r eval=FALSE}
starwars_df<-tbl_df(select(starwars,-films,-vehicles, -starships))
linkspotterComplete(starwars_df)$run_it
```
I remove "films","vehicles" and "starships" columns to stay on a standard dataset where every cell contains a single value.

I hope it helps.

Alassane
